language: generic

dist: focal

sudo: required

services:
  - docker

script:
  - docker build -t sjsj1123/docker-frontend  ./frontend
  - docker build -t sjsj1123/docker-backend   ./backend
  - docker build -t sjsj1123/docker-nginx     ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push sjsj1123/docker-frontend
  - docker push sjsj1123/docker-backend
  - docker push sjsj1123/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "Docker-fullstack-app-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-872515267023
  bucket_path: "docker-fullstack-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY