services:
  frontend:
    image: sjsj1123/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m
    networks:
      - app_network
  nginx:
    restart: always
    image: sjsj1123/docker-nginx
    ports:
      - "80:80"
    mem_limit: 128m
    networks:
      - app_network
  backend:
    image: sjsj1123/docker-backend
    networks:
      - app_network
    container_name : app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD:  $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT
    mem_limit: 128m
networks:
  app_network:
